### ISSUE TITLE
Include speed change event recording

### ISSUE THREAD

**Issue by jeremydaily** [nmfta-repo/nmfta-opentelematics-api#114]
In the parameters section, there should be a speed change threshold for recording speed events. For example, a common threshold for DDEC ecus is 7 mph/s. If this trigger is included, then a data table (a lot like DDEC Reports) should be available with 75 seconds of data available (60 seconds before and 15 seconds after). This data table could include speed, rpm, cruise status, brake status, clutch status, and fault codes.

**Comment by BenGardiner** [comment]
I need to check with collaborators about adding-back teh parameters link in the flagged events

**Comment by BenGardiner** [comment]
the new thresholds object would have to be linked to the Vehicle Flagged Event
