### ISSUE TITLE
Support 429 status for most endpoints

### ISSUE THREAD

**Issue by derek-zonar** [nmfta-repo/nmfta-opentelematics-api#118]
Currently the only "valid" responses are 200 and 401. A TSP may want to define a reasonable query rate for health checks and if exceeded by the user should be able to respond with a 429 status.

**Comment by BenGardiner** [comment]
Hi Derek, thank you again for the feedback. I agree and will take it a little further, infact.

In the *Rate-limit API Requests* section we stipulate that TSPs should rate-limit requests, so 429 should be an expected status code on more endpoints than just SOH.
