### ISSUE TITLE
Return 202 instead of 204 while processing export

### ISSUE THREAD

**Issue by derek-zonar** [nmfta-repo/nmfta-opentelematics-api#119]
204 indicates the request has been successfully completed and there is no further content for the client to receive. 202 indicates the request has been received but it still processing.

`The 204 (No Content) status code indicates that the server has
   successfully fulfilled the request and that there is no additional
   content to send in the response payload body.`

vs

`The 202 (Accepted) status code indicates that the request has been
   accepted for processing, but the processing has not been completed.`

**Comment by BenGardiner** [comment]
Derek, thank you! This seems like a nice refinement to me -- @jmpopper I'm assuming this change isn't a problem for you or the prototype?

**Comment by jmpopper** [comment]
@BenGardiner @derek-zonar -- Returning a 202 should be no problem at all!  Thank you.
