### ISSUE TITLE
duplicate .../stops/{id}

### ISSUE THREAD

**Issue by BenGardiner** [nmfta-repo/nmfta-opentelematics-api#139]

**Comment by BenGardiner** [comment]
@jmpopper : watch out for this in the prototype

**Comment by jmpopper** [comment]
Thanks @BenGardiner.  In the prototype we currently have a GET /stops/{stopId} endpoint and a PATCH /stops/{stopId} endpoint defined.  Is that correct?

**Comment by BenGardiner** [comment]
that is correct.
