### ISSUE TITLE
Get Vehicle Flagged Events should return a collection

### ISSUE THREAD

**Issue by BenGardiner** [nmfta-repo/nmfta-opentelematics-api#141]

**Comment by BenGardiner** [comment]
@jmpopper : watch out for this on `GET /v1.0/vehicles/{vehicleId}/flagged_events/{?startTime,stopTime}` in the prototype. I should return 

```
+ Response 200 (application/json)
    + Attributes (object)
        + data (array[Vehicle Flagged Event], fixed-type)
```

**Comment by jmpopper** [comment]
Thanks for the heads up @BenGardiner!  We are presently returning an array at this endpoint in the prototype.

**Comment by BenGardiner** [comment]
You did it right despite the docs :) . nice
