### ISSUE TITLE
Add localization to the OT API

### ISSUE THREAD

**Issue by BenGardiner** [nmfta-repo/nmfta-opentelematics-api#25]
from @ujonson : we need to either plan for and address localization of all enumerated contents and units

OR

at least include a footnote stating that localization is not part of this standard.

**Comment by BenGardiner** [comment]
@ujonson I don't think there is a way to do this *within* API blueprint.

We can use API blueprint to document how the API would respond-to and accept data from different locales. e.g. https://github.com/jsynowiec/api-blueprint-boilerplate/blob/10076ff164ebb89384a5ce47af4b86e9db8654fe/src/api.apib#L76

It can be done. If we're going to plan for localization then pragmatic thing to do is make all `enum[string]` members *opaque* tokens and provide some kind of lookup to deference them to translations.

OR 

we could just kick the can and stick with en_US only.

**Comment by ujonson** [comment]
If we are supporting Canada then I think it makes sense to write it into the standard now. I propose we make all the strings reference tokens and add an object to retrieve the proper strings based on language. If someone has an English only implementation they can still map everything on the backend.

**Comment by BenGardiner** [comment]
OK, lets do it
