### ISSUE TITLE
Use Case: Driver Availability - Add Driver Current Status

### ISSUE THREAD

**Issue by HVCSFriend** [nmfta-repo/nmfta-opentelematics-api#60]
Table 1 |   |  
-- | -- | --
Duty Status Categories |   |  
  |   |  
Duty Status | Abbreviation | Data Coding
Off Duty | OFF | 1
Sleeper Berth | SB | 2
Driving | D | 3
On-duty Not Driving | ON | 4

Table 2 |   |  
-- | -- | --
Categories   for Driver's Indication of Situations Impacting Driving Time Recording
  |   |  
  |   |  
Category | Abbreviation | Data Coding
Authorized Personal Use of CMV | PC | 1
Yard Moves | YM | 2
Default: None | --- | 0

**Comment by BenGardiner** [comment]
I don't know how to resolve this issue. I'll need more details please.

**Comment by HVCSFriend** [comment]
I see now that you have these 4 included as status_off, status_sb, status_d and status_on.

We may need 2 tree levels for these. For instance, I think On-duty Not Driving above is really comprised of: status_ym, status_wt, 

Status_on should include status_ym, 

Status_off should include status_pc, status_int-pc. But it was noted by the guy from Omnitracs last week that currently carriers may set time and/or distance limits for pc where it doesn't count against HOS, but the FMCSA should issue guidance on this.

What is an intermediate drive event (status_int_d)?
